# https://docs.ansible.com/projects/builder/en/latest/definition/
version: 3

images:
  base_image:
    name: registry.redhat.io/ubi8/ubi-minimal:latest
options:
    package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: "/usr/bin/python3"
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system: files/bindep.txt
  galaxy: files/requirements.yml
  python: files/requirements.txt

additional_build_files:
    - src: files/pip.conf
      dest: configs
    - src: files/ubi.repo
      dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/ubi.repo /etc/yum.repos.d/ubi.repo
  append_base:
    - RUN $PYCMD -m pip install --upgrade pip
  prepend_builder:
    - COPY _build/configs/pip.conf /etc/pip.conf
  append_final:
    - RUN ansible-galaxy collection install microsoft.ad
    - RUN $PKGMGR -y remove krb5-devel python3.12-devel